### ISSUE TITLE
Windows 7: FlashDevelop: infinite build loops.

### ISSUE THREAD

**Issue by sruloart** [lucamezzalira/haxe-watchify#3]
It happens with all of the targets AFAIK. It should stop trying to build the project after it encounters a build issue (with FlashDevelop especially, as there's an annoying bug where you can't delete/replace the files in the export directory).

Another, smaller issue, is that building the .swf file isn't very helpful with an OpenFL default build command because most people use the stand-alone player. You can add -web to the end of the Flash build command, so it would add an index.html file the user can use to test the .swf with. This index would be rebuilt on every build though, not sure if that's a problem. 

I'm really excited about this project, especially about the all
>GENERAL: live reload JS and Flash targets
 
Keep it up! :)

**Comment by lucamezzalira** [comment]
Hi, I don't have a Windows system configured on my macbook to try FlashDevelop yet, I'll do ASAP.
BTW it's correct that it's trying to rebuild a failing target because it's the point of automation build, so it's giving a feedback that something is going wrong in a particular build!

What do you think if I'll add the possibility to set the parameter to use in order to build an OpenFL project, so currently it's ```build``` by default but if you are able to set ```test``` could resolve the problem in your opinion? Or the workflow would be better with the ```-web``` parameter activate?

**Comment by sruloart** [comment]
I know :) my point is that on Windows building means opening another cmd process, and another one, and another one...my 16gb of RAM fills up completely in a few seconds. I've no clue as for why it's doing that.

I think that building / testing for Flash with Watchify means the user would have to use an index.html to quickly see the new builds. The stand-alone player won't re-open itself (building or testing), but a live-reloading index.html will reload the new .swf. 

So there are two options:  
1. You add -web: the user would then need to use something like live.js to reload the web page (it's generated by OpenFL every time, building or testing) which means it will also manually reload the new .swf. 
2. You make an index.html file of your own, containing a script to reload the .swf if it changes, or let the user to use something like: https://www.npmjs.com/package/simple-autoreload-server to watch his .swf by himself.

In every case it's not a big deal for the avid user.

**Comment by lucamezzalira** [comment]
FlashDevelop in order to use the completion server and have the code completion saves the file you are working every now on, that's why the watchify tool is going in build loop.
BTW I'll ask to Philippe, the creator of FlashDevelop, how it's working precisely and I'm going to understand if I can implement a workaround.

The idea to use an html page for Flash target is not bad at all, I'll investigate further on this topic, there was another suggestion to use halk live editing lib, I want to give it a try and see if it could fit better.

I keep you posted on that side!

**Comment by sruloart** [comment]
Halk support would be awesome :D 
This is the most updated version I'm aware of btw: https://github.com/profelis/halk2, but personally I couldn't get this to work with my set-up :|

**Comment by lucamezzalira** [comment]
I tried quickly yesterday without any fortune, I'll spend more time tonight.
Otherwise I'm going to ask information to its creator :P 

Anyway I could temporary starts to implement the solutions with live reload of an HTML page if I can't see any progress with Halk

**Comment by lucamezzalira** [comment]
Hi may I ask you to try setting as compiler the server instead of the normal compiler? Actually I had better performance with that on Windows
<img width="1022" alt="screen shot 2015-07-07 at 00 30 04" src="https://cloud.githubusercontent.com/assets/210272/8535630/77dc6b50-243f-11e5-8436-5700113255b7.png">

**Comment by sruloart** [comment]
The haxe build works great, it's the OpenFL version that keeps on creating new cmd and haxelib processes (cmd.exe*32, haxelib.exe*32), maybe it's something to do with haxelib? or at least the haxelib command. 

This long command isn't really needed:
Error: Command failed: C:\Windows\system32\cmd.exe /s /c `"haxelib run openfl build neko "`
^C

This command should be enough: 
`openfl build neko`

**Comment by lucamezzalira** [comment]
ok I'll give it a try, probably I'll be able to kill the current process before starting a new one.
I think in the next release with the live reload the performance on OpenFL target will be better

**Comment by lucamezzalira** [comment]
can you tell me in the meantime I'm checking the live reload feature on windows if this thing is resolved with the new version please?

**Comment by sruloart** [comment]
I can't use haxe-watchify at all because of issue #10 (it gives me the same error no matter how I try to use it, haxe or openfl, test or build, with a config file and without). I'll try forcing it to work :)

**Comment by lucamezzalira** [comment]
did you try to re-install it doing:

```
npm uninstall -g haxe-watchify
```

and then install it again from scratch?

**Comment by sruloart** [comment]
I did, but late last night, let me see...

**Comment by sruloart** [comment]
Nice! I've tested it pretty thoroughly and this issue is fixed! :D But I have more minor issues...

**Comment by lucamezzalira** [comment]
ok please document them in a new one issue, thanks for the test

**Comment by sruloart** [comment]
Oops, didn't see your message in time so I've opened 2 separate issues, but they aren't related :)

**Comment by lucamezzalira** [comment]
that's definitely fine, even better so I can work on them separately, you did the right choice
